<?php

declare(strict_types=1);

namespace App\Infrastructure\Persistence;

use PDO;
use PDOException;
use PDOStatement;
use RuntimeException;

/**
 * Wrapper around the PDO connection for PostgreSQL.
 *
 * - Built once by `bootstrap.php` from the `database` config block.
 * - Exposes `query()` with explicit per-type binding because PDO+PostgreSQL
 *   converts a PHP `false` to '' (empty string) which PostgreSQL rejects on
 *   BOOLEAN columns. Same workaround as the POC `Database::query()`.
 * - The class is the ONLY place in the codebase allowed to talk to PDO.
 *   Repositories receive a `PdoConnection` by constructor injection.
 */
final class PdoConnection
{
    private PDO $pdo;

    /**
     * @param array{host:string,port:int,name:string,user:string,password:string} $config
     */
    public function __construct(array $config)
    {
        $dsn = sprintf(
            'pgsql:host=%s;port=%d;dbname=%s',
            $config['host'],
            $config['port'],
            $config['name']
        );

        try {
            $this->pdo = new PDO($dsn, $config['user'], $config['password'], [
                PDO::ATTR_ERRMODE            => PDO::ERRMODE_EXCEPTION,
                PDO::ATTR_DEFAULT_FETCH_MODE => PDO::FETCH_ASSOC,
                PDO::ATTR_EMULATE_PREPARES   => false,
            ]);
        } catch (PDOException $e) {
            throw new RuntimeException('Database connection failed: ' . $e->getMessage(), (int) $e->getCode(), $e);
        }
    }

    /**
     * Prepares a statement, binds each parameter with the correct PDO type
     * and executes it. Returns the executed statement so the caller can
     * fetch / fetchAll / rowCount as needed.
     *
     * @param array<int|string, scalar|null> $params
     */
    public function query(string $sql, array $params = []): PDOStatement
    {
        $stmt = $this->pdo->prepare($sql);

        foreach ($params as $key => $value) {
            $placeholder = is_int($key) ? $key + 1 : ':' . $key;

            if (is_bool($value)) {
                $stmt->bindValue($placeholder, $value, PDO::PARAM_BOOL);
            } elseif (is_int($value)) {
                $stmt->bindValue($placeholder, $value, PDO::PARAM_INT);
            } elseif ($value === null) {
                $stmt->bindValue($placeholder, null, PDO::PARAM_NULL);
            } else {
                $stmt->bindValue($placeholder, (string) $value, PDO::PARAM_STR);
            }
        }

        $stmt->execute();
        return $stmt;
    }

    /**
     * Returns the underlying PDO for the rare cases where transactions or
     * driver-specific calls are needed (e.g. `lastInsertId`). Use sparingly.
     */
    public function pdo(): PDO
    {
        return $this->pdo;
    }

    /**
     * Convenience: returns the id generated by the most recent INSERT on
     * the given sequence. PostgreSQL needs the sequence name.
     */
    public function lastInsertId(string $sequenceName): int
    {
        return (int) $this->pdo->lastInsertId($sequenceName);
    }

    public function beginTransaction(): void
    {
        $this->pdo->beginTransaction();
    }

    public function commit(): void
    {
        $this->pdo->commit();
    }

    public function rollback(): void
    {
        $this->pdo->rollBack();
    }
}
